import type { StrategyConfig, StrategyType } from './types.ts';

export const STRATEGY_CONFIGS: Record<StrategyType, StrategyConfig> = {
  TREND: {
    name: 'TREND',
    enabled: true,
    allowedRegimes: ['STRONG_UP', 'UP'],
    allowedTimeframes: ['1h', '4h'],
    positionSizePercent: 0.25,
    maxPositionPercent: 0.35,
    maxOpenPositions: 2,
    entryParams: {
      minCompositeScore: 60,
      minExpectedReturn: 0.008,
    },
    exitParams: {
      stopLossMethod: 'atr',
      stopLossValue: 2.5,
      takeProfitMethod: 'atr',
      takeProfitValue: 2.0,
      trailingMethod: 'percent_giveback',
      trailingActivatePercent: 0.008,
      trailingParam: 0.30,
      timeKillBars: 4,
      timeKillMinMove: 0.007,
      breakEvenEnabled: true,
      breakEvenTriggerPercent: 0.015,
      breakEvenOffsetPercent: 0.001,
      quickKillEnabled: true,
      quickKillAfterBars: 2,
      quickKillMinGain: 0.006,
      quickKillSlTighten: 1.2,
    },
  },

  BREAKOUT: {
    name: 'BREAKOUT',
    enabled: true,
    allowedRegimes: ['STRONG_UP', 'UP', 'SIDEWAYS'],
    allowedTimeframes: ['1h'],
    positionSizePercent: 0.20,
    maxPositionPercent: 0.30,
    maxOpenPositions: 2,
    entryParams: {
      lookbackBars: 30,
      volumeMultiplier: 2.0,
      minAtrPercent: 0.3,
    },
    exitParams: {
      stopLossMethod: 'breakout_level',
      stopLossValue: 0,
      takeProfitMethod: 'atr',
      takeProfitValue: 3.0,
      trailingMethod: 'chandelier',
      trailingActivatePercent: 0.005,
      trailingParam: 2.0,
      timeKillBars: 8,
      timeKillMinMove: 0.01,
      breakEvenEnabled: false,
      breakEvenTriggerPercent: 0,
      breakEvenOffsetPercent: 0,
      quickKillEnabled: false,
      quickKillAfterBars: 0,
      quickKillMinGain: 0,
      quickKillSlTighten: 0,
    },
  },

  MEAN_REVERSION: {
    name: 'MEAN_REVERSION',
    enabled: true,
    allowedRegimes: ['SIDEWAYS', 'UP'],
    allowedTimeframes: ['15m'],
    positionSizePercent: 0.15,
    maxPositionPercent: 0.20,
    maxOpenPositions: 3,
    entryParams: {
      rsiThreshold: 30,
      bbPercentBThreshold: 0.15,
      maxAtrPercent: 3.0,
    },
    exitParams: {
      stopLossMethod: 'atr',
      stopLossValue: 1.5,
      takeProfitMethod: 'mean_target',
      takeProfitValue: 0,
      trailingMethod: 'none',
      trailingActivatePercent: 0,
      trailingParam: 0,
      timeKillBars: 4,
      timeKillMinMove: 0.003,
      breakEvenEnabled: false,
      breakEvenTriggerPercent: 0,
      breakEvenOffsetPercent: 0,
      quickKillEnabled: true,
      quickKillAfterBars: 2,
      quickKillMinGain: 0.002,
      quickKillSlTighten: 0.8,
    },
  },

  MOMENTUM: {
    name: 'MOMENTUM',
    enabled: true,
    allowedRegimes: ['STRONG_UP', 'UP'],
    allowedTimeframes: ['1h', '4h'],
    positionSizePercent: 0.20,
    maxPositionPercent: 0.30,
    maxOpenPositions: 2,
    entryParams: {
      histogramSpikeMultiplier: 1.5,
      rsiMin: 45,
      rsiMax: 75,
      volumeMultiplier: 1.0,
    },
    exitParams: {
      stopLossMethod: 'atr',
      stopLossValue: 2.0,
      takeProfitMethod: 'none',
      takeProfitValue: 0,
      trailingMethod: 'histogram_decay',
      trailingActivatePercent: 0,
      trailingParam: 0.50,
      timeKillBars: 6,
      timeKillMinMove: 0.005,
      breakEvenEnabled: true,
      breakEvenTriggerPercent: 0.01,
      breakEvenOffsetPercent: 0.001,
      quickKillEnabled: false,
      quickKillAfterBars: 0,
      quickKillMinGain: 0,
      quickKillSlTighten: 0,
    },
  },

  SCALP: {
    name: 'SCALP',
    enabled: false,
    allowedRegimes: ['STRONG_UP', 'UP', 'SIDEWAYS'],
    allowedTimeframes: ['15m'],
    positionSizePercent: 0.10,
    maxPositionPercent: 0.15,
    maxOpenPositions: 3,
    entryParams: {
      rsiPullbackMin: 35,
      rsiPullbackMax: 50,
      minVolumeRatio: 0.8,
    },
    exitParams: {
      stopLossMethod: 'atr',
      stopLossValue: 0.75,
      takeProfitMethod: 'atr',
      takeProfitValue: 1.0,
      trailingMethod: 'none',
      trailingActivatePercent: 0,
      trailingParam: 0,
      timeKillBars: 2,
      timeKillMinMove: 0.002,
      breakEvenEnabled: false,
      breakEvenTriggerPercent: 0,
      breakEvenOffsetPercent: 0,
      quickKillEnabled: false,
      quickKillAfterBars: 0,
      quickKillMinGain: 0,
      quickKillSlTighten: 0,
    },
  },
};

export function getEnabledStrategies(filter?: StrategyType[]): StrategyConfig[] {
  const all = Object.values(STRATEGY_CONFIGS).filter(s => s.enabled);
  if (!filter || filter.length === 0) return all;
  return all.filter(s => filter.includes(s.name));
}
